language: php

php:
  - 8.2
  - 8.3

dist: focal

addons:
  apt:
    packages:
      - libonig5

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - travis_retry composer install

script:
  - vendor/bin/phpunit
